# Stay on the Scala 3 LTS line (3.3.x), don't update to 3.4.x and later
updates.pin = [
  { groupId = "org.scala-lang", artifactId = "scala3-library", version = { prefix = "3.3." } },
  { groupId = "org.scala-lang", artifactId = "scala3-library_sjs1", version = { prefix = "3.3." } },
  { groupId = "org.scala-lang", artifactId = "scala3-library_native0.5", version = { prefix = "3.3." } },
  { groupId = "org.scala-lang", artifactId = "scala3-compiler", version = { prefix = "3.3." } }
]
