name: CI
on:
  push:
    branches:
    - master
    tags:
    - "v*"
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - uses: coursier/cache-action@v6
    - uses: coursier/setup-action@v1
      with:
        jvm: 8
        apps: sbt sbtn

    - name: Compile
      run: sbtn +test +mimaReportBinaryIssues

  readme:
    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - uses: coursier/cache-action@v6
    - uses: coursier/setup-action@v1
      with:
        jvm: 17
        apps: sbt sbtn

    - name: Compile
      run: sbtn readme/mdoc

  publish:
    needs: test
    if: github.event_name == 'push'
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v3
        with:
          fetch-depth: 0


      - uses: coursier/cache-action@v6
      - uses: coursier/setup-action@v1
        with:
          jvm: 8
          apps: sbt sbtn

      - run: .github/scripts/gpg-setup.sh
        env:
          PGP_SECRET: ${{ secrets.PUBLISH_SECRET_KEY }}

      - name: Release
        run: sbtn ci-release
        env:
          PGP_PASSPHRASE: ${{ secrets.PUBLISH_SECRET_KEY_PASSWORD }}
          PGP_SECRET: ${{ secrets.PUBLISH_SECRET_KEY }}
          SONATYPE_PASSWORD: ${{ secrets.PUBLISH_PASSWORD }}
          SONATYPE_USERNAME: ${{ secrets.PUBLISH_USER }}
